sudo: false
language: python
python:
- '3.6'
branches:
  only:
  - src
install:
- pip install --requirement requirements.txt
script:
- pushd web/
- nikola build
- popd
- touch web/output/.nojekyll
deploy:
- provider: pages
  skip_cleanup: true
  target_branch: master
  on:
    branch: src
  local_dir: web/output
  github_token: $GITHUB_TOKEN
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: fbRvaAGYCrt/WyZt/Vpuz26up89nu5CW4rMwOf+Go7gZIWaOfrUorC6KD0NPeE9xK/WjsJmi9vvJ7WBKuLHWJ3vVhrJ1Gyi9q3s9l3PcEm6J0wlPontMWu+sx96L6dc/rAlhSyr6XmhDnwX8oBGN17rR7U91bLj80FlisibuMN+SUAwiWcsIv7hyK35ntM6/70PNOIySUZdZE5GZ8l1gWDzgSpyVzAta3HBgpkIDhlV/OE3AmBUhqWYS/UKy7FoFb+mPHjk6S2gcs0N94MH2kgOfERk7doV0Kk/0/hsZnbQknykYa5L9YMg1XYikWCobdLB209F6MxuYSdQWACaTLDMu2/dAlHovkYD/+Yye9DQMVuAQtJTyK9niUTKnZAeDYxejVtiTPJZ8VfBfuphrG1k3e0DaibsHZSBaMiF7w0mGn6jCcKEqAQFgYj8TSYW/GkSyuLBgzi1GX2vi9siextr9wF5gzFGspLgf0ehggJsCYPdxGbvLyeaZruR8tid0/RORrOj4w9iRBF9NUfmQf35N9GeP3WdtO8MrhK9CZAhn5ykTGUfGkgQ2+6Kw/yS7VO6IiCgZ3Y5YQQNm5s19Lf99TV6JaszuzducwUfVkCXCIf6qaQLugWIngfx2oFGC5quMRaauQH6sfFboesoC1td1NbBToJBsGsrlZLKfV38=
